# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField()),
                ('Title', models.CharField(max_length=36)),
                ('Content', models.CharField(max_length=600)),
            ],
        ),
    ]
