# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 05:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160406_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmds',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 13, 48, 36, 733000), verbose_name=b'update time'),
        ),
        migrations.RemoveField(
            model_name='rdtooluser',
            name='group',
        ),
        migrations.AddField(
            model_name='rdtooluser',
            name='group',
            field=models.ManyToManyField(to='main.Group'),
        ),
    ]
