# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 02:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160406_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmd_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rdtoolcmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('help', models.CharField(max_length=256)),
                ('cmds_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cmd_Type')),
                ('param', models.ManyToManyField(to='main.Parameter')),
            ],
        ),
        migrations.AlterField(
            model_name='cmds',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 24, 10, 41, 0, 339000), verbose_name=b'update time'),
        ),
    ]
