# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160516_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-create_time'], 'verbose_name': 'Commands logs', 'verbose_name_plural': 'Commands logs'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='cmddone',
            field=models.DateTimeField(unique=True, verbose_name=b'cmd done'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='cmdstatus',
            field=models.CharField(max_length=50, unique=True, verbose_name=b'cmd done status'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='jumpboxrun',
            field=models.DateTimeField(unique=True, verbose_name=b'Run in Jumpbox'),
        ),
    ]
