# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160516_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='cmddone',
            field=models.DateTimeField(blank=True, verbose_name=b'cmd done'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='cmdstatus',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'cmd done status'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='jumpboxrun',
            field=models.DateTimeField(blank=True, verbose_name=b'Run in Jumpbox'),
        ),
    ]
