# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160516_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
    ]
